# Generated by Django 5.0.6 on 2024-05-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
