# Generated by Django 5.0.6 on 2024-05-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
