# Generated by Django 5.0.6 on 2024-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0008_paymentinformation_shippinginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('USER_Identification', models.CharField(default=None, max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='cvv',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiration_date',
            field=models.CharField(max_length=255),
        ),
    ]
